### ISSUE TITLE
Question about porting firmware to vial

### ISSUE THREAD

**Issue by HaoboGu** [yulei/amk#2]
Hello! I'm trying to porting my firmware to vial, but it seems that vial supports only qmk firmware. So I'm curious about how do you make your firmware recognized by vial? Thanks very much if you can help!

**Comment by yulei** [comment]
porting the vial HID protocol and implementing the keycode converer. you can check the codes at https://github.com/yulei/amk/tree/master/main/vial

**Comment by HaoboGu** [comment]
thanks for the reply! I noticed that amk used both threadx and freertos, how do you choose between them? I want to use one of them, but haven't decided yet.

**Comment by yulei** [comment]
threadx used too many memory for usb stack, thus freertos was a better choice.

**Comment by HaoboGu** [comment]
thanks very much!
