### ISSUE TITLE
GC_xx和AC_xx的区别

### ISSUE THREAD

**Issue by HaoboGu** [yulei/amk#3]
a锅好，我在看代码的时候有发现amk在定义keycode的时候，有好多个版本，比如TRNS，就有KC_TRNS、AC_TRNS、GC_TRNS，这些code都有什么区别呢？似乎在某种情况下，只有GC_xx生效？

**Comment by yulei** [comment]
kc是1个byte的，ac是2个byte, gc只是通过宏定义包裹了一下这两种

**Comment by HaoboGu** [comment]
但是实际上，2bytes和1byte的keycode都会用到是这样嘛，2bytes用于和vial通信以及存储，发送hid report实际上还是用的1byte的keycode

**Comment by yulei** [comment]
对，2byte用于内部处理。1byte那个是USB hid 的标准键值

**Comment by HaoboGu** [comment]
懂了，a锅nb！

另外，为啥我配置了vial之后，还是识别不上呢？vial_process()我这边是在对应的hid interface收到 set report之后触发：
```c
UINT USBD_HID_vial_SetReport(UX_SLAVE_CLASS_HID *hid_instance, UX_SLAVE_CLASS_HID_EVENT *hid_event) {
  UINT status = UX_SUCCESS;
  vial_process(hid_event->ux_device_class_hid_event_buffer, hid_event->ux_device_class_hid_event_length);
  return status;
}
```
但是似乎vial并不能识别到。。。
